Update styling of 'View Playlists' page
ryanhu021/csc307-team-project pull request #101
Opened 2023-12-02 00:25 UTC by nickbircher

2023-12-02 02:45 UTC, ktaschek requested changes
Linting error in the frontend: build did not complete.

2023-12-04 17:31 UTC, ryanhu021 approved these changes
Looks good!

2023-12-04 17:31 UTC, ryanhu021 commented on packages/frontend/src/component-styles/add-playlist-card.css
> +.add-playlist-container {
nit: we could try to migrate these css files to bootstrap classes or styled components if we have time

2023-12-04 21:25 UTC, ktaschek requested changes
New Playlist Card is not updated to have same sizing as the playlist cards

2023-12-04 21:35 UTC, ktaschek approved these changes
LGTM

2023-12-04 21:53 UTC, merged